version: "3.7"

services:

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/imaia_prest/Documents/Docker/docker_data/portainer:/data
    container_name: portainer

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/imaia_prest/Documents/Docker/docker_data/mongo:/data/db
    container_name: mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    container_name: mongo_express

  neo4j:
    image: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /home/imaia_prest/Documents/Docker/docker_data/neo4j:/data
    container_name: neo4j

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    volumes:
      - /home/imaia_prest/Documents/Docker/docker_data/redis:/data
    container_name: redis

  cassandra:
    image: cassandra
    restart: always
    ports:
      - 7000:7000
    volumes:
      - /home/imaia_prest/Documents/Docker/docker_data/cassandra:/var/lib/cassandra
    container_name: cassandra

  jupyter_all_spark:
    image: jupyter/all-spark-notebook
    restart: always
    ports:
      - 8888:8888
    container_name: jupyter_notebook
