version: "3.7"

services:

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/iurimaia/Documents/docker_data/portainer:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/iurimaia/Documents/docker_data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  neo4j:
      image: neo4j
      restart: always
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - /home/iurimaia/Documents/docker_data/neo4j:/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    volumes:
      - /home/iurimaia/Documents/docker_data/redis:/data

  cassandra:
    image: cassandra
    restart: always
    ports:
      - 7000:7000
    volumes:
      - /home/iurimaia/Documents/docker_data/cassandra:/var/lib/cassandra


